### ISSUE TITLE
ceph infernalis is using new gateway port "7480"

### ISSUE THREAD

**Issue by thomasalrin** [megamsys/radosgw-s3#22]
default port is "80" is old ceph(hammer 0.94).
We are using "80" port in `lib/s3/object.rb` `lib/s3/service.rb` `lib/s3/connection.rb` files.

**Comment by thomasalrin** [comment]
@vijaykanthm28 clear this issue, then only you can use ceph radosgw. To test temporarily, change in your local gem file.

**Comment by indykish** [comment]
@thomasalrin  Hey thomas thanks for the response.

**Comment by indykish** [comment]
@vijaykanthm28  Good job.  @thomasalrin  Seems like in the current `infernalis` install this doesn't appear to be an issue as @vijaykanthm28  front-ended by `apache2`. Its working now.

**Comment by thomasalrin** [comment]
@indykish cool:-)
